Comment out force failure step in build.yaml
Comment out the force failure step in the build workflow.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -28,5 +28,5 @@ jobs:
         run: ls -l target
 
 
-      - name: Force failure
-        run: exit 1
+      # - name: Force failure
+      #   run: exit 1
